name: dynamic_badges
description: Package being developed to help with material design badges implementation.
version: 0.0.5
repository: https://github.com/rdrgbaioco/dynamic_badges

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
